//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Miracle.Service.WebApi.Dal.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public long ContactId { get; set; }
        public long UserId { get; set; }
        public long SexId { get; set; }
        public System.DateTime Dob { get; set; }
        public string City { get; set; }
        public string MobileNumber { get; set; }
        public Nullable<long> RefererId { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<long> StatusId { get; set; }
        public string Name { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual User User { get; set; }
        public virtual LookupDIM LookupDIM { get; set; }
        public virtual User User1 { get; set; }
        public virtual LookupDIM LookupDIM1 { get; set; }
    }
}
