//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Miracle.Service.WebApi.Dal.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LookupCategoryDIM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LookupCategoryDIM()
        {
            this.LookupDIMs = new HashSet<LookupDIM>();
        }
    
        public long LookupCategoryId { get; set; }
        public string LookupCategoryDescription { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LookupDIM> LookupDIMs { get; set; }
    }
}
